Repository wecode-bootcamp-korea/19-1st-hikicovery-frontend, pull requests merged in 2021-04, with the labels that each got.

#4 [19기 김도희] 풋터 코드리뷰 리팩토링 완료
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/index.js
  src/styles/Common.scss
Labels: Status: 리뷰 요청

#8 [19기 손주영] Modify : README.md 수정
  README.md
Labels: Status: 리뷰 요청

#7 [19기 손주영] Add: 로그인 컴포넌트 레이아웃, Input기능 완료
  src/Routes.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginForm/LoginForm.js
  src/pages/Login/LoginForm/LoginForm.scss
  src/pages/Login/Logins.scss
  src/styles/Common.scss
Labels: Status: 리뷰 요청

#6 [19기 손주영] Modify : 백엔드 통신 완료, CSS, 함수 수정
  .eslintrc
  package-lock.json
  package.json
  src/Routes.js
  src/components/AccountBanner/AccountBanner.js
  src/components/AccountBanner/AccountBanner.scss
  src/pages/Signup/PremiumContents/PremiumContent.scss
  src/pages/Signup/PremiumContents/PremiumContents.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: 리뷰 진행중

#10 Add : 메인페이지 하단 레이아웃 , 링크 연결 , 백 서버 연결
  .eslintrc
  .prettierrc
  public/data/maindata.json
  public/data/promotiondata.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/pages/Detail/Detail.js
  src/pages/Detail/components/ProductContent/ProductContent.js
  src/pages/Detail/components/ProductContent/ProductReview.js
  src/pages/Detail/components/ProductDetail.js
  src/pages/Detail/components/ProductOption/PaymentTitle.js
  src/pages/Main/components/ContentBox/ContentItem.js
  src/pages/Main/components/ContentBox/ContentItem.scss
  src/pages/Main/components/ContentBox/ContentNewItem.js
  src/pages/Main/components/ContentBox/ContentNewItem.scss
  src/pages/Main/components/ContentBox/Promotion.js
  src/pages/Main/components/ContentBox/Promotion.scss
  src/pages/Main/components/MainContent/MainContent.js
  src/pages/Main/components/MainContent/MainContent.scss
Labels: Status: 리뷰 요청

#1 [19기 황재원]add: 제품리스트페이지 완료
  package-lock.json
  public/data/ShoesData.json
  src/pages/Cart/Cart.js
  src/pages/Shoes/Shoes.js
  src/pages/Shoes/Shoes.scss
  src/pages/Shoes/ShoesBestItem/ShoesBestItem.js
  src/pages/Shoes/ShoesBestItem/ShoesBestItem.scss
  src/pages/Shoes/ShoesCard/ShoesCard.js
  src/pages/Shoes/ShoesCard/ShoesCard.scss
  src/pages/Shoes/ShoesList/ShoesFilterButton.js
  src/pages/Shoes/ShoesList/ShoesFilterButton.scss
  src/pages/Shoes/ShoesList/ShoesList.js
  src/pages/Shoes/ShoesList/ShoesList.scss
  src/pages/Shoes/ShoesPaginate/ShoesPaginate.scss
  src/pages/Shoes/ShoesPaginate/ShoesPaginateNum.js
  src/pages/Shoes/ShoesPaginate/ShoesPaginateNum.scss
  src/pages/Shoes/ShoesTop/ShoesTop.js
  src/pages/Shoes/ShoesTop/ShoesTop.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#11 [19기 손주영] Add : 장바구니 컴포넌트 구현 완료
  src/Routes.js
  src/pages/Basket/Basket.js
  src/pages/Basket/Basket.scss
Labels: Status: 수정 요청

#13 [19기 김도희] Modify : 전체 검토
  src/Routes.js
  src/components/AccountBanner/AccountBanner.js
  src/components/AccountBanner/AccountBanner.scss
  src/components/FixMenuBar/FixMenuBar.js
  src/components/FixMenuBar/FixMenuBar.scss
  src/components/Nav/Nav.scss
  src/pages/Login/Login.js
  src/pages/Login/LoginForm/LoginForm.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/MainContent/MainContent.js
  src/pages/Signup/PremiumContents/PremiumContent.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: 리뷰 요청
